# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kanchi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BackGround = QtWidgets.QLabel(self.centralwidget)
        self.BackGround.setEnabled(True)
        self.BackGround.setGeometry(QtCore.QRect(-40, -40, 1291, 931))
        self.BackGround.setText("")
        self.BackGround.setPixmap(QtGui.QPixmap("images/Green Bgk.png"))
        self.BackGround.setScaledContents(True)
        self.BackGround.setObjectName("BackGround")
        self.Background2 = QtWidgets.QLabel(self.centralwidget)
        self.Background2.setGeometry(QtCore.QRect(-170, 240, 1401, 571))
        self.Background2.setText("")
        self.Background2.setPixmap(QtGui.QPixmap("images/Sky Blue.png"))
        self.Background2.setScaledContents(True)
        self.Background2.setObjectName("Background2")
        self.Background3 = QtWidgets.QLabel(self.centralwidget)
        self.Background3.setGeometry(QtCore.QRect(-30, 540, 1211, 421))
        self.Background3.setText("")
        self.Background3.setPixmap(QtGui.QPixmap("images/White.png"))
        self.Background3.setScaledContents(True)
        self.Background3.setObjectName("Background3")
        self.Kanchikt = QtWidgets.QLabel(self.centralwidget)
        self.Kanchikt.setGeometry(QtCore.QRect(330, 30, 151, 211))
        self.Kanchikt.setText("")
        self.Kanchikt.setPixmap(QtGui.QPixmap("images/Newari kt.png"))
        self.Kanchikt.setScaledContents(True)
        self.Kanchikt.setObjectName("Kanchikt")
        self.Kanchitext = QtWidgets.QLabel(self.centralwidget)
        self.Kanchitext.setGeometry(QtCore.QRect(490, 70, 221, 101))
        self.Kanchitext.setText("")
        self.Kanchitext.setPixmap(QtGui.QPixmap("images/Kanchi.png"))
        self.Kanchitext.setScaledContents(True)
        self.Kanchitext.setObjectName("Kanchitext")
        self.SwagatamLabel = QtWidgets.QLabel(self.centralwidget)
        self.SwagatamLabel.setGeometry(QtCore.QRect(420, 290, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SwagatamLabel.setFont(font)
        self.SwagatamLabel.setObjectName("SwagatamLabel")
        self.BolnaSuruButton = QtWidgets.QPushButton(self.centralwidget)
        self.BolnaSuruButton.setEnabled(True)
        self.BolnaSuruButton.setGeometry(QtCore.QRect(380, 380, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(True)
        self.BolnaSuruButton.setFont(font)
        self.BolnaSuruButton.setAutoFillBackground(False)
        self.BolnaSuruButton.setStyleSheet("color: white; background-color:#228B22; border-style:outset;border-radius:15px;")
        self.BolnaSuruButton.setObjectName("BolnaSuruButton")
        self.BolnaBandaButton = QtWidgets.QPushButton(self.centralwidget)
        self.BolnaBandaButton.setGeometry(QtCore.QRect(600, 380, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.BolnaBandaButton.setFont(font)
        self.BolnaBandaButton.setAutoFillBackground(False)
        self.BolnaBandaButton.setStyleSheet("color: white; background-color:#d32f2f; border-style:outset;border-radius:15px;")
        self.BolnaBandaButton.setObjectName("BolnaBandaButton")
        self.SuruGarnaLabel = QtWidgets.QLabel(self.centralwidget)
        self.SuruGarnaLabel.setGeometry(QtCore.QRect(380, 500, 351, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.SuruGarnaLabel.setFont(font)
        self.SuruGarnaLabel.setObjectName("SuruGarnaLabel")
        self.SunekaKuraharuLabel = QtWidgets.QLabel(self.centralwidget)
        self.SunekaKuraharuLabel.setGeometry(QtCore.QRect(460, 610, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SunekaKuraharuLabel.setFont(font)
        self.SunekaKuraharuLabel.setObjectName("SunekaKuraharuLabel")
        self.OutputTextboxLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputTextboxLabel.setGeometry(QtCore.QRect(190, 670, 771, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.OutputTextboxLabel.setFont(font)
        self.OutputTextboxLabel.setText("")
        self.OutputTextboxLabel.setObjectName("OutputTextboxLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.BolnaSuruButton.clicked.connect(lambda: self.clicked("This Was Clicked"))
    

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SwagatamLabel.setText(_translate("MainWindow", "तपाइलाई स्वागत छ"))
        self.BolnaSuruButton.setStatusTip(_translate("MainWindow", "बोल्न सुरु has been pressed"))
        self.BolnaSuruButton.setText(_translate("MainWindow", "बोल्न सुरु"))
        self.BolnaBandaButton.setStatusTip(_translate("MainWindow", "बोल्न बन्द has been pressed"))
        self.BolnaBandaButton.setText(_translate("MainWindow", "बोल्न बन्द"))
        self.SuruGarnaLabel.setText(_translate("MainWindow", "सुरु गर्नाको लागी \" बोल्न सुरु \" थिच्नुहोस् "))
        self.SunekaKuraharuLabel.setText(_translate("MainWindow", "सुनेको कुराहरु:"))

    def clicked(self,text):
        self.SunekaKuraharuLabel.setText(text)
        self.SunekaKuraharuLabel.adjustSize()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
